#!/bin/bash

# Maintenance Access
DB_USER="trtel.backup"
DB_PASS="Telus2017#"
REPORT_DATE=$(date '+%Y-%m-%d')  # Automatically set the report date to the current date
DIR="backup"

# Create Directory if not exists
mkdir -p "${DIR}"

# Debug logs file
LOG_FILE="${DIR}/debug.log"
: > "${LOG_FILE}" # Clear log file

# Define the function to generate queries
function generateQuery {
    local serverType="${1}"
    local locationConstraint="${2}"

    local queryStr="SELECT b.server AS Server, TRUNCATE(((SUM(b.size) / 1024) / 1024), 2) AS size_MB, s.location AS Location, s.type AS DB_engine, s.os AS OS FROM daily_log b JOIN servers s ON s.name = b.server WHERE b.backup_date = '${REPORT_DATE}' ${locationConstraint} AND s.type='${serverType}' GROUP BY b.server, s.location, s.type, s.os;"

    echo "${queryStr}"
}

# Function to append section to email content with textual representation of data
appendSection() {
    local title="${1}"
    local query="${2}"

    echo "Appending section: ${title}" >> "${LOG_FILE}"
    echo "Query: ${query}" >> "${LOG_FILE}"

    {
        echo "<h2 style='margin-top: 20px; color: #4B286D;'>${title}</h2>"
        mysql --defaults-file=/etc/mysql.cnf --defaults-group-suffix=bk -u"${DB_USER}" -p"${DB_PASS}" -D "${DB_MAINTENANCE}" -e "${query}" --batch --skip-column-names 2>>"${LOG_FILE}" | while IFS=$'\t' read -r Server size_MB Location DB_engine OS; do
            echo "<div style='margin-bottom: 10px;'>"
            echo "  <strong>Server:</strong> ${Server}<br>"
            echo "  <strong>Size:</strong> ${size_MB} MB<br>"
            echo "  <strong>Location:</strong> ${Location}<br>"
            echo "  <strong>DB Engine:</strong> ${DB_engine}<br>"
            echo "  <strong>OS:</strong> ${OS}<br>"
            echo "</div>"
        done
    } >> "${emailFile}" 

    if [[ $? -ne 0 ]]; then
        echo "Query execution failed for section: ${title}" >> "${LOG_FILE}"
    else
        echo "Query executed successfully for section: ${title}" >> "${LOG_FILE}"
    fi
}

# Clear the terminal screen
clear

# Generate Queries
queryMySQL=$(generateQuery "MYSQL" "AND s.location='GCP'")
queryPGSQL=$(generateQuery "PGSQL" "AND s.location='GCP'")
queryMSSQL=$(generateQuery "MSSQL" "AND s.location='GCP'")

# Log the generated queries
echo "Generated Queries:" >> "${LOG_FILE}"
echo "${queryMySQL}" >> "${LOG_FILE}"
echo "${queryPGSQL}" >> "${LOG_FILE}"
echo "${queryMSSQL}" >> "${LOG_FILE}"

# Email Content
emailFile="${DIR}/yvette_email_notification.html"
{
    echo "<!DOCTYPE html>"
    echo "<html lang='en'>"
    echo "<head>"
    echo "  <meta charset='UTF-8'>"
    echo "  <title>Daily Backup Data Overview</title>"
    echo "  <style>"
    echo "    body { font-family: Arial, sans-serif; background-color: #f4f4f4; color: #333; margin: 0; padding: 20px; }"
    echo "    .container { max-width: 800px; margin: 0 auto; padding: 20px; background-color: #fff; border: 1px solid #ddd; border-radius: 10px; }"
    echo "    h1 { color: #4B286D; text-align: center; }"
    echo "    h2 { color: #4B286D; }"
    echo "    .footer { text-align: center; padding: 20px; color: #4B286D; border-top: 1px solid #ddd; margin-top: 20px; }"
    echo "  </style>"
    echo "</head>"
    echo "<body>"
    echo "  <div class='container'>"
    echo "    <h1>Daily Backup Data Overview - ${REPORT_DATE}</h1>"
} > "${emailFile}"

# Append sections to the email content
appendSection "GCP Backup Information - MYSQL" "${queryMySQL}"
appendSection "GCP Backup Information - PGSQL" "${queryPGSQL}"
appendSection "GCP Backup Information - MSSQL" "${queryMSSQL}"

# Close HTML Tags
{
    echo "    <div class='footer'>"
    echo "      <p>Report generated by Database Engineering</p>"
    echo "    </div>"
    echo "  </div>"
    echo "</body>"
    echo "</html>"
} >> "${emailFile}"

# Display Email Content File's Path for Debug
echo "Email content generated at: ${emailFile}"
echo "Log file generated at: ${LOG_FILE}"

# Send Email via sendmail
{
    echo "To: yvette.halili@telusinternational.com"
    echo "From: no-reply@telusinternational.com"
    echo "MIME-Version: 1.0"
    echo "Content-Type: text/html; charset=utf-8"
    echo "Subject: [Test - susweyak17] Daily Backup Report - ${REPORT_DATE}"
    echo ""
    cat "${emailFile}"
} | /usr/sbin/sendmail -t

echo "Email sent to yvette.halili@telusinternational.com"
